# Generated by Django 3.0.6 on 2020-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
